name: target-matrix-example

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
      - next/*
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - next/*

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      include: "this should not be empty: ${{ steps.define.include }}"
    steps:
      - name: Define Cross-Compilation Target Matrix
        id: define
        uses: dherman/target-matrix@v0.0.1
        with:
          toolchain: rust
          windows-latest: x86_64-pc-windows-msvc
          macos-latest: x86_64-apple-darwin
          ubuntu-latest: x86_64-unknown-linux-gnu x86_64-unknown-freebsd x86_64-unknown-openbsd

  build:
    needs: matrix
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     include: ${{ toJson(needs.matrix.include) }}
    steps:
      - name: Show Target
        id: show
        # run: echo "${{ matrix.target }}"
        run: echo "${{ needs.matrix.include }}"
